<?php

require_once '/usr/share/php/fkooman/Jwt/autoload.php';
require_once '/usr/share/php/fkooman/OAuth/Server/autoload.php';
require_once '/usr/share/php/fkooman/SeCookie/autoload.php';
require_once '/usr/share/php/fkooman/SqliteMigrate/autoload.php';
require_once '/usr/share/php/LC/Common/autoload.php';
require_once '/usr/share/php/ParagonIE/ConstantTime/autoload.php';
require_once '/usr/share/php/Psr/Log/autoload.php';
// optional support for php-saml-sp
if (file_exists('/usr/share/php/fkooman/SAML/SP/autoload.php')) {
	require_once '/usr/share/php/fkooman/SAML/SP/autoload.php';
}

// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                ___CLASSLIST___
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require ___BASEDIR___$classes[$cn];
        }
    },
    ___EXCEPTION___,
    ___PREPEND___
);
// @codeCoverageIgnoreEnd
