name: Check

on: [push, pull_request]

jobs:
  build:
    name: Check
    runs-on: ubuntu-20.04
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get install -y git composer colordiff
        composer global require vimeo/psalm
        #todo: composer global require friendsofphp/php-cs-fixer does not work
        wget https://cs.symfony.com/download/php-cs-fixer-v2.phar -O php-cs-fixer
        sudo chmod a+x php-cs-fixer
        sudo mv php-cs-fixer /usr/local/bin/php-cs-fixer
        (
          cd ..
          git clone https://github.com/fantostisch/vpn-lib-common
          cd vpn-lib-common
          composer install
        )
        composer install

    - name: check
      run: |
        export PATH="$PATH:$HOME/.composer/vendor/bin"
        sudo chmod +x ./check.sh
        ./check.sh

